apiVersion: v1
kind: Service
metadata:
  name: data-web-app-service
  labels:
    app: data-web-app
    component: web
spec:
  selector:
    app: data-web-app
    version: v1
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: data-web-app-postgres
  labels:
    app: data-web-app
    component: postgres
spec:
  selector:
    app: data-web-app
    component: postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
